/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydslcov.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydslcov.MyDslCovRuntimeModule;
import org.xtext.example.mydslcov.MyDslCovStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MyDslCovIdeSetup extends MyDslCovStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MyDslCovRuntimeModule(), new MyDslCovIdeModule()));
	}
	
}
