/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydslcov.ide;


/**
 * Use this class to register ide components.
 */
public class MyDslCovIdeModule extends AbstractMyDslCovIdeModule {
}
