/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydslcov;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MyDslCovStandaloneSetup extends MyDslCovStandaloneSetupGenerated {

	public static void doSetup() {
		new MyDslCovStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
